# Simplified Firebase Deploy
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List repository structure
        run: |
          echo "=== Repository structure ==="
          find . -type f -name "package.json" | head -5
          echo "=== Pokemon golden cards directory ==="
          ls -la pokemon-golden-cards/ || echo "Directory not found"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Check package.json
        run: |
          echo "=== Contents of pokemon-golden-cards/package.json ==="
          cat pokemon-golden-cards/package.json
          
      - name: Install dependencies
        run: |
          cd pokemon-golden-cards
          echo "Installing dependencies..."
          npm install
          
      - name: Build project
        run: |
          cd pokemon-golden-cards
          echo "Building project..."
          npm run build
          echo "Copying dist to root..."
          cp -r dist ../dist
          echo "Contents of root dist:"
          ls -la ../dist/
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POKEMON_CTPSS }}
          channelId: live
          projectId: pokemon-ctpss
